workspace: "/Volumes/Extreme SSD/NCI/2022-09-06"
optim_root: "/Volumes/Extreme SSD/NCI/2022-09-06"
country_list: "/Users/hawthornespatial/Projects/WBNCI/code/natural-capital-index/src/configs/country_lists/2022-09-06-final.txt"
n_workers: 10
national_boundaries: "/Volumes/Extreme SSD/NCI/inputs/national_boundaries/countries_iso3_NCI_trimmed.shp"
succession_file: "/Volumes/Extreme SSD/NCI/inputs/scenario_construction/potential_vegetation/succession_matrix.csv"
lu_table_file: "/Volumes/Extreme SSD/NCI/inputs/lulc_codes.csv"
sdu_area: 0.1
base:
  current_lulc: "/Volumes/Extreme SSD/NCI/inputs/current_lulc/modifiedESA_2022_06_03.tif"
  pixel_area: "/Volumes/Extreme SSD/NCI/inputs/pixel_area/ESACCI-LC-L4-LCCS-Map-300m-P1Y-2015-v2.0.7_pixel_area_km2.tif"
scenario_creation:
  potential_vegetation: "/Volumes/Extreme SSD/NCI/inputs/scenario_construction/potential_vegetation/potential_vegetation.tif"
  protected_areas: "/Volumes/Extreme SSD/NCI/inputs/scenario_construction/protected_areas/wdpa_merged.tif"
  slope_threshold_expansion: "/Volumes/Extreme SSD/NCI/inputs/scenario_construction/ag_slope_exclusion_masks/expansion_full.tif"
  slope_threshold_intensification: "/Volumes/Extreme SSD/NCI/inputs/scenario_construction/ag_slope_exclusion_masks/intensification_full.tif"
  rainfed_suitability: "/Volumes/Extreme SSD/NCI/inputs/scenario_construction/ag_crop_suitability_maps/rainfed_mask_ESAaligned.tif"
  irrigated_suitability: "/Volumes/Extreme SSD/NCI/inputs/scenario_construction/ag_crop_suitability_maps/irrigation_mask_ESAaligned.tif"
  riparian_buffer: "/Volumes/Extreme SSD/NCI/inputs/scenario_construction/riparian_buffer_location/riparian_buffer_mask_md5_6184cf8ea3ce479e1a0538fc49df2175.tif"
  sustainable_irrigation: "/Volumes/Extreme SSD/NCI/inputs/scenario_construction/ag_irrigation_potential/sustainable_irrigation_mask.tif"
  soil_suitability: "/Volumes/Extreme SSD/NCI/inputs/scenario_construction/ag_natural_expansion_potential/suitability_expansion_potential_mask_ESAaligned.tif"
carbon:
  carbon_zone_file: "/Volumes/Extreme SSD/NCI/inputs/carbon/new_ecoregions.tif"
  carbon_table_file: "/Volumes/Extreme SSD/NCI/inputs/carbon/carbon_table_2022-08-10.csv"
cropland:
  crop_value_current: "/Volumes/Extreme SSD/NCI/inputs/cropland/oil_palm_split/totalproductionvaluecurrent_NoPalmOilRevR_nolabor_machinerycosts.tif"
  crop_value_intensified_irrigated: "/Volumes/Extreme SSD/NCI/inputs/cropland/oil_palm_split/totalproductionvalueirrigated_NoPalmOilRevR_nolabor_machinerycosts.tif"
  crop_value_intensified_rainfed: "/Volumes/Extreme SSD/NCI/inputs/cropland/oil_palm_split/totalproductionvaluerainfed_NoPalmOilRevR_nolabor_machinerycosts.tif"
  palm_oil_value: "/Volumes/Extreme SSD/NCI/inputs/cropland/oil_palm_split/totalproductionvaluecurrent_OnlyPalmOilRevR_nolabor_machinerycosts.tif"
forestry:
  forestry_value: "/Volumes/Extreme SSD/NCI/inputs/forestry/forestry_land_share_return_tcost_before_2022_07_23.tif"
grazing:
  grazing_potential_value: "/Volumes/Extreme SSD/NCI/inputs/grazing/potential_meat_returns-t_per_ha_global_price_landshare_md5_d7cfbe4828d5b9a2e11ef1b6e2ccc174.tif"
  grazing_potential_methane: "/Volumes/Extreme SSD/NCI/inputs/grazing/potential_methane_filled_0.5_md5_9a8735eb022a44bc5a00b809bea69bcb.tif"
biodiversity:
  predicts_table_1: "/Volumes/Extreme SSD/NCI/inputs/biodiversity/2022_07_05/predicts_July_2022.csv"
  predicts_table_2: "/Volumes/Extreme SSD/NCI/inputs/biodiversity/2022_07_05/predicts2_July_2022.csv"
  data_root: "/Volumes/Extreme SSD/NCI/inputs/biodiversity/GlobalLayers"
  plantation_raster: "/Volumes/Extreme SSD/NCI/inputs/biodiversity/GlobalLayers/plantation_2022_06_03.tif"
transition_cost:
  data_root: "/Volumes/Extreme SSD/NCI/inputs/transition_costs"
optimization_output_folder: "OptimizationResults"
objectives:
  - "net_econ_value"
  - "biodiversity"
  - "net_ghg_co2e"
optimization_scenarios:
  - "extensification_bmps_irrigated"
  - "extensification_bmps_rainfed"
  - "extensification_current_practices"
  - "extensification_intensified_irrigated"
  - "extensification_intensified_rainfed"
  - "fixedarea_bmps_irrigated"
  - "fixedarea_bmps_rainfed"
  - "fixedarea_intensified_irrigated"
  - "fixedarea_intensified_rainfed"
  - "forestry_expansion"
  - "grazing_expansion"
  - "restoration"
  - "sustainable_current"
